### ISSUE TITLE
feat: follow system theme

### ISSUE THREAD

**Issue by ghost** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#182]
just sync it with the os 🥴

**Comment by AnonymousWP** [comment]
This should be an option; not the default.

**Comment by Rudxain** [comment]
I'm willing to contribute to this. However, I'm still trying to get familiarized with the codebase.

[`dark-light` doesn't provide `async`](https://docs.rs/dark-light/1.1.1/dark_light/#functions) API, so color-scheme can only be efficiently synced on app startup. We could use a polling mechanism to update in real-time, but that seems overkill, since most users won't frequently change the DE theme while UAD is running.

In the future, we could copy some code from Firefox (is `MPL-2.0` compatible with `GPL-3.0`?), to update in real-time in an event-driven way

**Comment by AnonymousWP** [comment]
It's fine if it's only on start-up. If it's not too much work it's a nice bonus, but not mandatory for sure.🙂

**Comment by Rudxain** [comment]
#650 #627
