### ISSUE TITLE
Remove com.sec.android.diagmonagent from recommended packages

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#350]
### List your packages

com.sec.android.diagmonagent says in the app description that it spams the crash log, overheats the phone, and drains battery. There is no reason this should be a recommended package.

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
Thanks for reporting, but next time please stick to the issue template. I'll get this fixed.

**Comment by AnonymousWP** [comment]
Hmm, this is a difficult one; it sends diagnostics to Samsung, which makes it recommended, but then making the device overheat is a serious problem too. I'm thinking of making it `Advanced` *and* put a warning in the description.

Do you know if this problem also occurs when uninstalling the package instead of disabling?

**Comment by Lost-Entrepreneur439** [comment]
I'm unsure, it was my friend who noticed this on her S22 Ultra and she didn't want to try uninstalling it, I don't have any modern Samsung devices personally.

**Comment by AnonymousWP** [comment]
Okay, and would you be okay with the idea I proposed?

**Comment by Lost-Entrepreneur439** [comment]
Yes

**Comment by d0ob** [comment]
Hi there ! 
Sorry to post on a closed issue, I have a question related :

From Canta, which is apparently fetching informations from here, that bloat is still recommended to remove ; Has it been proven safe to remove since ? Or is it old infos ?

Thanks for all the work, in any case, treasur of information !

**Comment by AnonymousWP** [comment]
You could go through some open issues and see if it was reported by someone. If that's the case, please open a PR.
