### ISSUE TITLE
bug(uninstalling): can't uninstall apps on legacy Android versions, even when rooted

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#401]
### Describe the bug

Nothing appears to happen when uninstalling apps on older Android versions, I am unsure of the exact versions affected, however this issue does occur on my Motorola Milestone 3 (model number XT860, codename umts_solana) running CyanogenMod 10.1 (Android 4.2.2). In the wiki, it mentions you need root for Android Jellybean and earlier, but I'm rooted and still can't uninstall anything.

### Expected behavior

I'd expect UAD to actually uninstall the application.

### Provide logs

[UAD_20240402.log](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/files/14836487/UAD_20240402.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Tsumetaayz** [comment]
The program uses the --user option to uninstall apps, Jelly Bean doesn't understand the "user" as it was not existent back then.
a solution would be an option for rooted devices in the program that removes the --user key to remove it with root privileges.
example: ADB shell pm uninstall "com.package.name" instead of ADB shell pm uninstall --user 0 "com.package.name", which JB can't run.

**Comment by Frigyes06** [comment]
We could add a setting to remove the user tag, or detect android version and do it automatically.

**Comment by lavafroth** [comment]
This behavior does not seem to be triggered by the `--user` flag (see the logs) since we check for the android sdk. [This xda thread](https://xdaforums.com/t/need-help-removing-system-apps-through-adb-on-4-4-2-kitkat-phone.4123943/) mentions `pm block`.
Our code in `sync.rs` is deferring to `pm uninstall` instead of `pm block` for SDK versions below 19 (@Lost-Entrepreneur439 has a device with SDK version 17). I'll follow up with a PR tomorrow.
