### ISSUE TITLE
meta(pkg-lists): Move `uad_lists` to a separate repository

### ISSUE THREAD

**Issue by Artem13327** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#612]
### Describe the feature you want

This list is used not only by this application and I think it would be good if it was developed in a separate repository

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Rudxain** [comment]
I totally agree! This would also make PRs and Issues more organized.

The file is embedded into the UAD-ng binary at compile-time:
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/821587d0454b5227a1e0f495cec9129d171cb576/src/core/uad_lists.rs#L219

So we have 2 (or more?) options:
1. Always try to download an updated list.
    - This relies on the network, so the user should open UAD-ng for the 1st time, as soon as the program is downloaded (to ensure internet is available)
2. Use a macro that downloads the file (from the other repo) at compile-time, and embed it.
    - This seems complicated, but it's technically possible (Rust macros are "black magic" ✨️)

See also #608

**Comment by Rudxain** [comment]
I would've preferred this thread to be a Discussion rather than an Issue. But I guess it's fine as-is

**Comment by AnonymousWP** [comment]
We can do this with 2.0.0, as it's a breaking change. Let's talk about the details once we get close to that (hopefully ever).

**Comment by samolego** [comment]
Also, you could probably use git subdirs to not hassle with macros for the embeding at compile time.

**Comment by Rudxain** [comment]
> git subdirs

Do you mean sub-modules? I've heard of them, but I only have a vague idea of how they work

**Comment by samolego** [comment]
Ah yeah the submodules. Basically you embed another repo in this one and you'd be able to copy it via path, maybe even reuse current code with just dir names changed? I'm not sure how it's embedded in the program currently.

**Comment by crash5** [comment]
I don't know the rust ecosystem but in the CI pipeline you can simply download the latest uad json from the uad repo and overwrite the one came with the source code. Nothing really has to change anywhere else. (I would avoid any git submodul magic for a simple thing like this).

For the separation, at first I think it will be enough if users can load the uad json file from the filesystem and use it. Not at as a mandatory step, just an option instead using the "embedded" one. Afer the program can use the uad json from "anywhere" for the next step can be an update button which simply check some version file from the new repo to see if there is a new version available and show an option to download it. (maybe can be an option to where to look for the uad json file in the local filesytem, and use it if it is readable instead of the embedded one). So it will slowly transfer to the external uad json file usage.

**Comment by AnonymousWP** [comment]
> I would've preferred this thread to be a Discussion rather than an Issue. But I guess it's fine as-is

I see where you're coming from. I think a Discussion would be better too, as you can't just PR files by moving them to another repo. This only involves 1 repo (a delete). I'm converting it to a Discussion.
